version: '3'
services:
    neo4j:
        image: neo4j:latest
        ports:
            - "7687:7687"
            - "7474:7474"
            - "7473:7473"
        volumes:
            - ../:/var/lib/neo4j/import
        environment: 
            - NEO4J_AUTH=neo4j/test
            - NEO4J_dbms_memory_pagecache_size=1G
            - NEO4J_dbms.memory.heap.initial_size=1G
            - NEO4J_dbms_memory_heap_max__size=1G